# 神經網路計算(一)

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [11]:
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

#### 第一層：三個神經元

In [43]:
W1=np.array([[0.1,0.2, 0.3,0.4, 0.5], [0.2,0.3, 0.4,0.5, 0.6],[0.3,0.4,0.5,0.6,0.7],[0.4,0.5,0.6,0.7,0.8,],[0.5,0.6,0.7,0.8,0.9],[0.6,0.7,0.8,0.9,1.0]])
b1=np.array([0.1, 0.2, 0.3,0.4,0.5])

In [44]:
print(X.shape)
print(W1.shape)
print(b1.shape)

(6,)
(6, 5)
(5,)


In [30]:
z1=np.dot(X, W1)+b1
print(z1)
print(z1.shape)

[ 9.2 11.4 13.6 15.8 18. ]
(5,)


In [31]:
h1=relu(z1)
print(h1)
print(h1.shape)

[ 9.2 11.4 13.6 15.8 18. ]
(5,)


#### 第二層：兩個神經元

In [35]:
W2=np.array([[0.1, 0.2,0.3,0.4], [0.2,0.3,0.4, 0.5], [0.3,0.4,0.5, 0.6],[0.4,0.5,0.6,0.7],[0.5,0.6,0.7,0.8]])
b2=np.array([0.1, 0.2,0.3,0.4])

In [36]:
print(h1.shape)
print(W2.shape)
print(b2.shape)

(5,)
(5, 4)
(4,)


In [37]:
z2=np.dot(h1, W2)+b2
print(z2)
print(z2.shape)

[22.7 29.6 36.5 43.4]
(4,)


In [45]:
h2=relu(z2)
print(h2)
print(h2.shape)

[22.7 29.6 36.5 43.4]
(4,)


#### 第三層(輸出層)：兩個神經元

In [39]:
W3=np.array([[0.1,0.2, 0.3,0.4], [0.2,0.3, 0.4,0.5],[0.3,0.4,0.5,0.6],[0.4,0.5,0.6,0.7]])
b3=np.array([0.1, 0.2,0.3,0.4])

In [40]:
print(h2.shape)
print(W3.shape)
print(b3.shape)

(4,)
(4, 4)
(4,)


In [41]:
z3=np.dot(h2, W3)+b3
print(z3)
print(z3.shape)

[36.6  49.92 63.24 76.56]
(4,)


In [42]:
y_hat=softmax(z3)
print(y_hat)

[4.42172562e-18 2.69397952e-12 1.64133333e-06 9.99998359e-01]


In [46]:
W4 = np.array([
    [0.5, 0.3, 0.1],
    [0.2, 0.4, 0.6],
    [0.7, 0.5, 0.3],
    [0.6, 0.2, 0.4]])

b4 = np.array([0.4, 0.5, 0.6])
print(W4.shape)
print(b4.shape)

(4, 3)
(3,)


In [48]:
z4 = np.dot(W3, W4) + b4
print(z4)
print(z4.shape)

[[0.94 0.84 0.98]
 [1.14 0.98 1.12]
 [1.34 1.12 1.26]
 [1.54 1.26 1.4 ]]
(4, 3)


In [49]:
y_hat = softmax(z4)
print(y_hat)
print(y_hat.shape)

[[0.06555413 0.05931583 0.06822944]
 [0.08006799 0.06822944 0.07848254]
 [0.09779527 0.07848254 0.09027641]
 [0.11944741 0.09027641 0.10384259]]
(4, 3)


In [50]:
y = np.array([0, 0, 1])

In [56]:

def cross_entropy_error(y_hat, y):
  return -np.sum(y * np.log(y_hat + 1e-7))

In [57]:
loss = cross_entropy_error(y_hat, y) #  y_hat 與 y 之間的誤差值
print(f'y_hat 與 y 之間的誤差值: {loss}')

y_hat 與 y 之間的誤差值: 9.899511569718133


In [51]:
!pip install gradio

In [52]:

import gradio as gr

In [53]:
def dnn(*x):
  x = np.array(x, dtype=float)

  z1 = np.dot(x, W1) + b1
  h1 = relu(z1)

  z2 = np.dot(h1, W2) + b2
  h2 = relu(z2)

  z3 = np.dot(h2, W3) + b3
  h3 = sigmoid(z3)

  z4 = np.dot(h3, W4) + b4
  y_hat_func = softmax(z4)

  return f'預測類別: {int(np.argmax(y_hat)) + 1}', y_hat_func

In [54]:

iface = gr.Interface(dnn,
            inputs=[gr.Number(label=f'特徵值 {i+1}') for i in range(6)],
            outputs=[
                gr.Textbox(label='預測類別'),
                gr.Textbox(label='y_hat 數值')],
            title='DNN 類別預測',
            description='請輸入6個特徵值')
iface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://aaea63b6b0d08b1f60.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [55]:

_, y_hat_func = dnn(X)
print(y_hat_func) # dnn結果的y_hat
print(y_hat) # 第1項練習的y_hat

if np.allclose(y_hat_func, y_hat):
  print(f'函數dnn()的 y_hat 與第1項練習的 y_hat 相同\n')
else:
  print(f'函數dnn()的 y_hat 與第1項練習的 y_hat 不同\n')


[[0.43920315 0.26639018 0.29440668]]
[[0.06555413 0.05931583 0.06822944]
 [0.08006799 0.06822944 0.07848254]
 [0.09779527 0.07848254 0.09027641]
 [0.11944741 0.09027641 0.10384259]]
函數dnn()的 y_hat 與第1項練習的 y_hat 不同

